const FUNCHEAP_CITY_TO_REGION: Record<string, string> = {
    // San Francisco
    "San Francisco": "San Francisco",

    // East Bay
    "Alameda": "East Bay",
    "Albany": "East Bay",
    "Antioch": "East Bay",
    "Berkeley": "East Bay",
    "Brentwood": "East Bay",
    "Clayton": "East Bay",
    "Concord": "East Bay",
    "Danville": "East Bay",
    "Dublin": "East Bay",
    "El Cerrito": "East Bay",
    "Emeryville": "East Bay",
    "Fremont": "East Bay",
    "Hayward": "East Bay",
    "Hercules": "East Bay",
    "Lafayette": "East Bay",
    "Livermore": "East Bay",
    "Martinez": "East Bay",
    "Moraga": "East Bay",
    "Newark": "East Bay",
    "Oakland": "East Bay",
    "Oakley": "East Bay",
    "Orinda": "East Bay",
    "Piedmont": "East Bay",
    "Pinole": "East Bay",
    "Pittsburg": "East Bay",
    "Pleasant Hill": "East Bay",
    "Pleasanton": "East Bay",
    "Richmond": "East Bay",
    "San Leandro": "East Bay",
    "San Pablo": "East Bay",
    "San Ramon": "East Bay",
    "Union City": "East Bay",
    "Walnut Creek": "East Bay",

    // North Bay
    "American Canyon": "North Bay",
    "Belvedere": "North Bay",
    "Benicia": "North Bay",
    "Calistoga": "North Bay",
    "Cloverdale": "North Bay",
    "Corte Madera": "North Bay",
    "Cotati": "North Bay",
    "Dixon": "North Bay",
    "Fairfax": "North Bay",
    "Fairfield": "North Bay",
    "Healdsburg": "North Bay",
    "Larkspur": "North Bay",
    "Mill Valley": "North Bay",
    "Napa": "North Bay",
    "Novato": "North Bay",
    "Petaluma": "North Bay",
    "Rio Vista": "North Bay",
    "Rohnert Park": "North Bay",
    "Ross": "North Bay",
    "St. Helena": "North Bay",
    "San Anselmo": "North Bay",
    "San Rafael": "North Bay",
    "Santa Rosa": "North Bay",
    "Sausalito": "North Bay",
    "Sebastopol": "North Bay",
    "Sonoma": "North Bay",
    "Suisun City": "North Bay",
    "Tiburon": "North Bay",
    "Vacaville": "North Bay",
    "Vallejo": "North Bay",
    "Windsor": "North Bay",
    "Yountville": "North Bay",

    // Peninsula
    "Atherton": "Peninsula",
    "Belmont": "Peninsula",
    "Brisbane": "Peninsula",
    "Burlingame": "Peninsula",
    "Colma": "Peninsula",
    "Daly City": "Peninsula",
    "East Palo Alto": "Peninsula",
    "Foster City": "Peninsula",
    "Half Moon Bay": "Peninsula",
    "Hillsborough": "Peninsula",
    "Menlo Park": "Peninsula",
    "Millbrae": "Peninsula",
    "Pacifica": "Peninsula",
    "Palo Alto": "Peninsula",
    "Portola Valley": "Peninsula",
    "Redwood City": "Peninsula",
    "San Bruno": "Peninsula",
    "San Carlos": "Peninsula",
    "San Mateo": "Peninsula",
    "South San Francisco": "Peninsula",
    "Woodside": "Peninsula",

    // South Bay
    "Campbell": "South Bay",
    "Cupertino": "South Bay",
    "Gilroy": "South Bay",
    "Los Altos": "South Bay",
    "Los Altos Hills": "South Bay",
    "Los Gatos": "South Bay",
    "Milpitas": "South Bay",
    "Monte Sereno": "South Bay",
    "Morgan Hill": "South Bay",
    "Mountain View": "South Bay",
    "San Jose": "South Bay",
    "Santa Clara": "South Bay",
    "Saratoga": "South Bay",
    "Sunnyvale": "South Bay"
};

export function mapCityToRegion(city: string, platform: string) : string{
    if(platform === "funcheapsf"){
        return FUNCHEAP_CITY_TO_REGION[city] || "Other";
    }
    return "";
}
