const FUNCHEAP_CITY_TO_REGION: Record<string, string> = {
    // San Francisco
    "San Francisco": "San Francisco",

    // East Bay
    "Alameda": "East Bay",
    "Albany": "East Bay",
    "Antioch": "East Bay",
    "Berkeley": "East Bay",
    "Brentwood": "East Bay",
    "Clayton": "East Bay",
    "Concord": "East Bay",
    "Danville": "East Bay",
    "Dublin": "East Bay",
    "El Cerrito": "East Bay",
    "Emeryville": "East Bay",
    "Fremont": "East Bay",
    "Hayward": "East Bay",
    "Hercules": "East Bay",
    "Lafayette": "East Bay",
    "Livermore": "East Bay",
    "Martinez": "East Bay",
    "Moraga": "East Bay",
    "Newark": "East Bay",
    "Oakland": "East Bay",
    "Oakley": "East Bay",
    "Orinda": "East Bay",
    "Piedmont": "East Bay",
    "Pinole": "East Bay",
    "Pittsburg": "East Bay",
    "Pleasant Hill": "East Bay",
    "Pleasanton": "East Bay",
    "Richmond": "East Bay",
    "San Leandro": "East Bay",
    "San Pablo": "East Bay",
    "San Ramon": "East Bay",
    "Union City": "East Bay",
    "Walnut Creek": "East Bay",

    // North Bay
    "American Canyon": "North Bay",
    "Belvedere": "North Bay",
    "Benicia": "North Bay",
    "Calistoga": "North Bay",
    "Cloverdale": "North Bay",
    "Corte Madera": "North Bay",
    "Cotati": "North Bay",
    "Dixon": "North Bay",
    "Fairfax": "North Bay",
    "Fairfield": "North Bay",
    "Healdsburg": "North Bay",
    "Larkspur": "North Bay",
    "Mill Valley": "North Bay",
    "Napa": "North Bay",
    "Novato": "North Bay",
    "Petaluma": "North Bay",
    "Rio Vista": "North Bay",
    "Rohnert Park": "North Bay",
    "Ross": "North Bay",
    "St. Helena": "North Bay",
    "San Anselmo": "North Bay",
    "San Rafael": "North Bay",
    "Santa Rosa": "North Bay",
    "Sausalito": "North Bay",
    "Sebastopol": "North Bay",
    "Sonoma": "North Bay",
    "Suisun City": "North Bay",
    "Tiburon": "North Bay",
    "Vacaville": "North Bay",
    "Vallejo": "North Bay",
    "Windsor": "North Bay",
    "Yountville": "North Bay",

    // Peninsula
    "Atherton": "Peninsula",
    "Belmont": "Peninsula",
    "Brisbane": "Peninsula",
    "Burlingame": "Peninsula",
    "Colma": "Peninsula",
    "Daly City": "Peninsula",
    "East Palo Alto": "Peninsula",
    "Foster City": "Peninsula",
    "Half Moon Bay": "Peninsula",
    "Hillsborough": "Peninsula",
    "Menlo Park": "Peninsula",
    "Millbrae": "Peninsula",
    "Pacifica": "Peninsula",
    "Palo Alto": "Peninsula",
    "Portola Valley": "Peninsula",
    "Redwood City": "Peninsula",
    "San Bruno": "Peninsula",
    "San Carlos": "Peninsula",
    "San Mateo": "Peninsula",
    "South San Francisco": "Peninsula",
    "Woodside": "Peninsula",

    // South Bay
    "Campbell": "South Bay",
    "Cupertino": "South Bay",
    "Gilroy": "South Bay",
    "Los Altos": "South Bay",
    "Los Altos Hills": "South Bay",
    "Los Gatos": "South Bay",
    "Milpitas": "South Bay",
    "Monte Sereno": "South Bay",
    "Morgan Hill": "South Bay",
    "Mountain View": "South Bay",
    "San Jose": "South Bay",
    "Santa Clara": "South Bay",
    "Saratoga": "South Bay",
    "Sunnyvale": "South Bay"
};

const INDYBAY_CITY_TO_REGION: Record<string, string> = {
    // City of San Francisco
    "san francisco": "City of San Francisco",

    // East Bay Area
    "alameda": "East Bay Area",
    "albany": "East Bay Area",
    "antioch": "East Bay Area",
    "berkeley": "East Bay Area",
    "brentwood": "East Bay Area",
    "byron": "East Bay Area",
    "castro valley": "East Bay Area",
    "concord": "East Bay Area",
    "crockett": "East Bay Area",
    "danville": "East Bay Area",
    "discovery bay": "East Bay Area",
    "dublin": "East Bay Area",
    "el cerrito": "East Bay Area",
    "el sobrante": "East Bay Area",
    "emeryville": "East Bay Area",
    "fremont": "East Bay Area",
    "hayward": "East Bay Area",
    "hercules": "East Bay Area",
    "kensington": "East Bay Area",
    "lafayette": "East Bay Area",
    "livermore": "East Bay Area",
    "martinez": "East Bay Area",
    "moraga": "East Bay Area",
    "newark": "East Bay Area",
    "oakland": "East Bay Area",
    "orinda": "East Bay Area",
    "piedmont": "East Bay Area",
    "pinole": "East Bay Area",
    "pittsburg": "East Bay Area",
    "pleasant hill": "East Bay Area",
    "pleasanton": "East Bay Area",
    "richmond": "East Bay Area",
    "rodeo": "East Bay Area",
    "san leandro": "East Bay Area",
    "san lorenzo": "East Bay Area",
    "san pablo": "East Bay Area",
    "union city": "East Bay Area",
    "walnut creek": "East Bay Area",

    // Peninsula
    "atherton": "Peninsula",
    "belmont": "Peninsula",
    "brisbane": "Peninsula",
    "burlingame": "Peninsula",
    "colma": "Peninsula",
    "daly city": "Peninsula",
    "east palo alto": "Peninsula",
    "foster city": "Peninsula",
    "half moon bay": "Peninsula",
    "hillsborough": "Peninsula",
    "menlo park": "Peninsula",
    "millbrae": "Peninsula",
    "pacifica": "Peninsula",
    "portola valley": "Peninsula",
    "redwood city": "Peninsula",
    "san bruno": "Peninsula",
    "san carlos": "Peninsula",
    "san mateo": "Peninsula",
    "south san francisco": "Peninsula",
    "woodside": "Peninsula",

    // North Bay / Marin
    "belvedere": "North Bay / Marin",
    "calistoga": "North Bay / Marin",
    "corte madera": "North Bay / Marin",
    "cotati": "North Bay / Marin",
    "fairfax": "North Bay / Marin",
    "greenbrae": "North Bay / Marin",
    "healdsburg": "North Bay / Marin",
    "kentfield": "North Bay / Marin",
    "larkspur": "North Bay / Marin",
    "mill valley": "North Bay / Marin",
    "napa": "North Bay / Marin",
    "novato": "North Bay / Marin",
    "petaluma": "North Bay / Marin",
    "rohnert park": "North Bay / Marin",
    "ross": "North Bay / Marin",
    "san anselmo": "North Bay / Marin",
    "san rafael": "North Bay / Marin",
    "sausalito": "North Bay / Marin",
    "sebastopol": "North Bay / Marin",
    "sonoma": "North Bay / Marin",
    "st helena": "North Bay / Marin",
    "santa rosa": "North Bay / Marin",
    "tiburon": "North Bay / Marin",
    "windsor": "North Bay / Marin",
    "yountville": "North Bay / Marin",
    "american canyon": "North Bay / Marin",

    // South Bay Area
    "campbell": "South Bay Area",
    "cupertino": "South Bay Area",
    "gilroy": "South Bay Area",
    "los altos": "South Bay Area",
    "los altos hills": "South Bay Area",
    "los gatos": "South Bay Area",
    "milpitas": "South Bay Area",
    "monte sereno": "South Bay Area",
    "morgan hill": "South Bay Area",
    "mountain view": "South Bay Area",
    "palo alto": "South Bay Area",
    "san jose": "South Bay Area",
    "santa clara": "South Bay Area",
    "saratoga": "South Bay Area",
    "stanford": "South Bay Area",
    "sunnyvale": "South Bay Area",

    // Santa Cruz / Monterey Bay Area
    "aptos": "Santa Cruz / Monterey Bay Area",
    "capitola": "Santa Cruz / Monterey Bay Area",
    "carmel": "Santa Cruz / Monterey Bay Area",
    "carmel-by-the-sea": "Santa Cruz / Monterey Bay Area",
    "marina": "Santa Cruz / Monterey Bay Area",
    "monterey": "Santa Cruz / Monterey Bay Area",
    "pacific grove": "Santa Cruz / Monterey Bay Area",
    "salinas": "Santa Cruz / Monterey Bay Area",
    "santa cruz": "Santa Cruz / Monterey Bay Area",
    "scotts valley": "Santa Cruz / Monterey Bay Area",
    "seaside": "Santa Cruz / Monterey Bay Area",
    "soquel": "Santa Cruz / Monterey Bay Area",
    "watsonville": "Santa Cruz / Monterey Bay Area"
};

export function mapCityToRegion(city: string, platform: string) : string{
    if(platform === "funcheapsf"){
        return FUNCHEAP_CITY_TO_REGION[city] || "Other";
    }else if(platform === "indybay"){
        return INDYBAY_CITY_TO_REGION[city.toLowerCase()] || "California";
    }
    return "";
}
